# Acesse https://aka.ms/customizecontainer para saber como personalizar seu contêiner de depuração e como o Visual Studio usa este Dockerfile para criar suas imagens para uma depuração mais rápida.

# Esta fase é usada durante a execução no VS no modo rápido (Padrão para a configuração de Depuração)
FROM mcr.microsoft.com/dotnet/runtime:8.0 AS base
USER app
WORKDIR /app


# Esta fase é usada para compilar o projeto de serviço
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Development
WORKDIR /src
COPY ["worker/worker/worker.csproj", "worker/"]
COPY ["worker/Infra.InversionControl/Infra.InversionControl.csproj", "Infra.InversionControl/"]
COPY ["worker/Domain/domain.csproj", "Domain/"]
COPY ["worker/Infra.Data/Infra.Data.csproj", "Infra.Data/"]
COPY ["worker/Services/Services.csproj", "Services/"]
RUN dotnet restore "./worker/worker.csproj"
COPY . .
WORKDIR "/src/worker"
RUN dotnet build "./worker/worker.csproj" -c $BUILD_CONFIGURATION -o /app/build

# Esta fase é usada para publicar o projeto de serviço a ser copiado para a fase final
FROM build AS publish
ARG BUILD_CONFIGURATION=Development
RUN dotnet publish "./worker/worker.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# Esta fase é usada na produção ou quando executada no VS no modo normal (padrão quando não está usando a configuração de Depuração)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "worker.dll"]